import { UnifiedId } from ".";

export enum GameEventTypes {
  PLAYER_AFK = "PLAYER_AFK",
  COMBAT_REPORT = "COMBAT_REPORT",
  UNIT_COMBAT_ATTACK_CANCELLED = "UNIT_COMBAT_ATTACK_CANCELLED",
  PLANET_CAPTURED = "PLANET_CAPTURED",
  STATION_DESTROYED = "STATION_DESTROYED",
  UNIT_MOVEMENT_BOUNCED = "UNIT_MOVEMENT_BOUNCED",
  UNIT_STARVED_BY_OOS = "UNIT_STARVED_BY_OOS",
  UNIT_DESTROYED_IN_COMBAT = "UNIT_DESTROYED_IN_COMBAT",
  PLAYER_CYCLE_COMPLETED = "PLAYER_CYCLE_COMPLETED",
  GAME_CYCLE_COMPLETED = "GAME_CYCLE_COMPLETED",
  GAME_COMPLETED = "GAME_COMPLETED",
  GAME_STARTED = "GAME_STARTED",
  PLAYER_JOINED = "PLAYER_JOINED",
  PLAYER_LEFT = "PLAYER_LEFT",
  PLAYER_CONCEDED = "PLAYER_CONCEDED",
  PLAYERS_TRADED_PRESTIGE = "PLAYERS_TRADED_PRESTIGE",
  PLAYERS_TRADED_RENOWN = "PLAYERS_TRADED_RENOWN",
  PLAYER_CONSTRUCTED_STATION = "PLAYER_CONSTRUCTED_STATION",
  PLAYER_DECOMMISSIONED_STATION = "PLAYER_DECOMMISSIONED_STATION",
  UNIT_DEPLOYED = "UNIT_DEPLOYED"
}

export interface GameEvent {
  _id: UnifiedId;
  gameId: UnifiedId;
  playerId: UnifiedId | null;

  tick: number;
  type: GameEventTypes;
  data: object;
}
