export enum ERROR_CODES {
  REQUEST_VALIDATION_FAILED = "REQUEST_VALIDATION_FAILED",

  AUTH_TOKEN_MISSING_ID = "AUTH_TOKEN_MISSING_ID",
  AUTH_INVALID_GOOGLE_TOKEN = "AUTH_INVALID_GOOGLE_TOKEN",
  AUTH_FAILED = "AUTH_FAILED",

  USER_UNAUTHORIZED = "USER_UNAUTHORIZED",
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_JOINED_GAME = "USER_ALREADY_JOINED_GAME",
  USER_NOT_IN_GAME = "USER_NOT_IN_GAME",

  GAME_ID_REQUIRED = "GAME_ID_REQUIRED",
  GAME_NOT_FOUND = "GAME_NOT_FOUND",
  GAME_IS_NOT_ACTIVE = "GAME_IS_NOT_ACTIVE",
  GAME_IS_NOT_PENDING = "GAME_IS_NOT_PENDING",

  GAME_IS_FULL = "GAME_IS_FULL",
  GAME_NO_CAPITAL_AVAILABLE = "GAME_NO_CAPITAL_AVAILABLE",
  GAME_NO_SECOND_PLANET_AVAILABLE = "GAME_NO_SECOND_PLANET_AVAILABLE",
  GAME_NOT_ENOUGH_SPAWN_HEXES = "GAME_NOT_ENOUGH_SPAWN_HEXES",

  HEX_ID_INVALID = "HEX_ID_INVALID",
  HEX_OCCUPIED_BY_STATION = "HEX_OCCUPIED_BY_STATION",
  HEX_OCCUPIED_BY_UNIT = "HEX_OCCUPIED_BY_UNIT",
  HEX_INVALID_SPAWN_LOCATION = 'HEX_INVALID_SPAWN_LOCATION',

  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  PLAYER_DOES_NOT_OWN_HEX = "PLAYER_DOES_NOT_OWN_HEX",
  PLAYER_DOES_NOT_OWN_A_CAPITAL = 'PLAYER_DOES_NOT_OWN_A_CAPITAL',
  PLAYER_INSUFFICIENT_PRESTIGE = "PLAYER_INSUFFICIENT_PRESTIGE",

  STATION_NOT_FOUND = "STATION_NOT_FOUND",

  UNIT_ID_INVALID = "UNIT_ID_INVALID",
  UNIT_NOT_FOUND = "UNIT_NOT_FOUND",
  UNIT_IS_REGROUPING = "UNIT_IS_REGROUPING",
  UNIT_INSUFFICIENT_AP = 'UNIT_INSUFFICIENT_AP',
  UNIT_HAS_NOT_DECLARED_ATTACK = 'UNIT_HAS_NOT_DECLARED_ATTACK',
  UNIT_TEMPLATE_NOT_FOUND = 'UNIT_TEMPLATE_NOT_FOUND',
  UNIT_IS_AT_MAX_STEPS = 'UNIT_IS_AT_MAX_STEPS',
  UNIT_SPECIALIST_ID_REQUIRED = 'UNIT_SPECIALIST_ID_REQUIRED',
  UNIT_SPECIALIST_ID_INVALID = 'UNIT_SPECIALIST_ID_INVALID',
  UNIT_INVALID_UPGRADE_TYPE = 'UNIT_INVALID_UPGRADE_TYPE'
}
